### ISSUE TITLE
[Super-Issue] Further implementation of Hilbert configuration parser and server/client-side CLI tools

### ISSUE THREAD

**Issue by porst17** [hilbert/hilbert-cli#14]
## This super-issue is about further implementing/extending parts of [Configuration Design](https://github.com/hilbert/hilbert-cli/issues/13), remaining after merging PR (#34):

- [x] Fix `x11vnc` BG service (https://github.com/hilbert/hilbert-cli/pull/44/commits/6c6abf84fb3b20584634bc275034ab2f65764988)
- [x] Configuration Validator: `validation of unknown fields` (#36)
- [x] Configuration Validator: complex general validation (#37)
- [x] Make use of Travis CI (#1)
- [x] Add Travis CI Badge to the README page. 
- [x] Fix generation of `OGL.tgz` for `OpenGL` usage from within docker containers
- [x] cleanup directory structure / legacy files (https://github.com/hilbert/hilbert-cli/pull/44/commits/3ecb4c452467efe319526905dc0f84c59c434547)
- [x] improve client-side CLI (?). 
- [x] choose ~Python 2~ or Python 3 for the server-side tool (#76)
- [x] implement the computation of the set of stations within a `Group`  (#15)
- [x] Management Image should mount the Station SSH Access DB. See: (#25)
- [x] implement the handling/checking of `Profile::supported_types` (#32)
- [x] External hosting of configuration data, software and whatnot (#29)
- [x] ~~consider switching from `argparse` to some argument parser with sub-commands, e.g.   `http://click.pocoo.org/5/`, `https://github.com/docopt/docopt`.~~
- [x] ~~Design **configuration presets** (#30)~~

Add more unit-tests as `/tests/test_*.py`, e.g. using `pytest` (Note: data files may be in `/tests/data/`):
 - [x] `validation of unknown fields`: (#36)
 - [x] `DockerComposeService` & `DockerComposeApplication`: (#19)
 - [x] `Group` (inherit from `BaseRecordValidator`) (#15)
 - [x] `Profile::supported_types` (#32)

Note: unfinished parts of older super-issue hilbert/hilbert-docker-images#28 are to be merged into this one.

**Comment by porst17** [comment]
To be worked on later:
- Support of **configurable aliases** for subcommands and external scripts (#33) 
- Configuration Validator: modularity (e.g. validation with a json schema) (#35)
- finish missing checks in Validators (#78)
- forward logging options from server tool to remote driver (#77)
